name: watching_app_2
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+9

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  html: ^0.15.5
  http: ^1.3.0
  video_player: ^2.9.3
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  sizer: ^3.0.0
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  connectivity_plus: ^6.1.3
  webview_flutter: ^4.8.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  flutter_staggered_animations: ^1.1.1
  dio: ^5.8.0+1
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  image_gallery_saver: ^2.0.3
  flutter_wallpaper_manager: ^0.0.4
  device_info_plus: ^11.3.0
  flutter_svg: ^2.0.17
  flutter_keyboard_visibility: ^6.0.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  url_launcher: ^6.3.1
  uni_links: ^0.5.1
  share_plus: ^10.1.4
  wakelock_plus: ^1.2.10
  logger: ^2.5.0
  get_it: ^8.0.3
  file_picker: ^8.3.2
  open_file: ^3.5.10
  package_info_plus: ^8.3.0
  local_auth: ^2.3.0
  visibility_detector: ^0.4.0+2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  retry: ^3.1.2
  pub_semver: ^2.2.0
  firebase_analytics: 11.1.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/extensions/
    - assets/categories.json
    - assets/stars.json
    - assets/images/
    - assets/json/
